name: we_grow
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.3
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.0.1
    image_picker: ^0.6.7+7
    firebase_core: ^0.4.4+3
    firebase_auth: ^0.15.3
    cloud_firestore: ^0.13.0+1
    firebase_storage: ^3.1.6
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true

    assets:
    - assets/images/
fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-AltBold.otf
          weight: 750
        - asset: assets/fonts/ProximaNova-AltLight.otf
          weight: 200
        - asset: assets/fonts/ProximaNova-AltThin.otf
          weight: 350
        - asset: assets/fonts/ProximaNova-Black.otf
          weight: 400
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/ProximaNova-Thin.otf
          weight: 300